import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from './components/Theme-provider';
import MobileNav from './components/Navigation/MobileNav';
import { Toaster } from '@/components/ui/toaster';

const space = Space_Grotesk({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Kevin Lim: Fullstack Developer Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={space.className}>
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem disableTransitionOnChange>
          <MobileNav />
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
